import localFont from 'next/font/local'
import './globals.css'
import Navbar from '@/components/layout/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import Footer from '@/components/layout/footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='h-full'>
      <body className={`h-full flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Navbar />
          <main className='flex-grow'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
